spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xx?rewriteBatchedStatements=true
    username: 
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
    elasticsearch:
      enable: false
      url: http://localhost:9200
  cache:
    type: redis
  mail:
    host: 
    port: 
    protocol: 
    default-encoding: 
    username: 
    password: 
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

token-login:
  encrypt-str-aes-key: 
  test: true

moe:
  encrypt-str-aes-key: 7859635890493635
  video-base-path: https://xx/resource
  default-video-path: https://xx/resource/video/default.mp4
  bili-session: 
  bv-url: https://xx/bv
  bv-proxy-prefix: https://xx
  proxy-prefix: https://xx?url=
  local-file-service:
    enable: true
    file-base-path: 
    url-prefix: /common/image
# 限制视频转码 redis key    moe:limit:transform_video 有值就行
# 轮播图    moe:recommend_carousel   写id，用分号隔开
# 公告     moe:announcement
#  [
#    "java.util.ArrayList",
#    [
#      {
#        "@class": "com.abdecd.moebackend.business.pojo.vo.notice.Notice",
#        "title": "先消也上西应资",
#        "content": "consequat tempor et est",
#        "date": "1998-11-01",
#        "hash": "4261148C"
#      }
#    ]
#  ]

ali:
  oss:
    enable: true
    access-key-id: 
    access-key-secret: 
    bucket-name: 
    endpoint: 
    url-prefix: 
    sts-region-id: 
    sts-endpoint: 
    sts-role-arn: 
    sts-duration-seconds: 900
    sts-max-size: 2_147_483_648 # 2GB
    watermark: 

# mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'base'
      paths-to-match: '/**'
      packages-to-scan: com.abdecd.moebackend.business.controller.base
    - group: 'backstage'
      paths-to-match: '/**'
      packages-to-scan: com.abdecd.moebackend.business.controller.backstage
