name: Test before Merge
on:
  pull_request:
    branches:
      - try-test
    paths:
      - 'business/**' # 替换 'your-folder/' 为你要监控的文件夹路径

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH Keys
        run: |
          echo "this is an error"
          exit 1
